updated delete-objects

diff --git a/s3/bash-scripts/delete-bucket b/s3/bash-scripts/delete-bucket
--- a/s3/bash-scripts/delete-bucket
+++ b/s3/bash-scripts/delete-bucket
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Exit immediately if any command exits with a non-zero status
+set -e
+
 # Check if the first argument is provided (bucket name)
 if [ -z "$1" ]; then
   echo "No bucket name provided. (s3://my-bucket)"
